### ISSUE TITLE
Help with pty.js

### ISSUE THREAD

**Issue by coderaiser** [soliton4/nodeMirror#14]
Hi, nodeMirror is great project, I just looked how it works on linux, it's amazing :).
The most  exiting is terminal, which could be re sized in any way, and even synchronized across tabs. I work on similar [project](http://cloudcmd.io) and have problem with [pty](https://github.com/chjj/pty.js/) maybe you could help me with. I wrote author of this module (with pull requrests), but he must be to busy.

The thing is, when I use terminal for just typing commands everything good, but when I try to start `mc` error occurs and all screen looks corrupted. I saw that rows and cols count is some how changes to 24 80. But I could not understand how and where it could be.
There is sourceses for [client](https://github.com/coderaiser/cloudcmd/blob/dev/lib/client/terminal.js#L90-L135) and [server](https://github.com/coderaiser/cloudcmd/blob/dev/lib/server/terminal.js#L74-L94)

I will be grateful for your advice.

**Comment by soliton4** [comment]
@coderaiser it took me a while

your request was actually the inspiration for making a video 

https://www.youtube.com/watch?v=WEux3hSrMCE

the resize topic is handled in part 2. enjoy!
