### ISSUE TITLE
With Internet Explorer 10, pg-up or pg-down causes the "active line" and cursor to get out of sync

### ISSUE THREAD

**Issue by mebersole** [soliton4/nodeMirror#16]
The active blue line will highlight a line different from where the cursor is currently at.

If you need a video, let me know.  I was unable to reproduce this in Chrome or Firefox - myself and another person reproduced the IE10 bug, so not just my system.

**Comment by soliton4** [comment]
@mebersole is this still happening?

**Comment by soliton4** [comment]
i guess not
