### ISSUE TITLE
Copy-paste into terminal window

### ISSUE THREAD

**Issue by isusanin** [soliton4/nodeMirror#19]
Currently, there is no way to paste from clipboard into the terminal window command prompt.

**Comment by soliton4** [comment]
yes there is.
it works on chrome / firefox in kde
i noticed that it didnt work in windows, but i have no idea why

**Comment by soliton4** [comment]
it appears to be a bug in this library:
https://github.com/chjj/term.js

maybe you should open a bugreport there.
if they fix it, let me know, i will put the latest version in nodeMirror

**Comment by isusanin** [comment]
Never mind, it actually works! I'm testing in Windows 8/Chrome. You just have to press Ctrl+A before Ctrl+V. It's all described on this page: https://github.com/chjj/term.js

**Comment by soliton4** [comment]
cool
