### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by mhk** [soliton4/nodeMirror#24]
Following the installation instructions in [Usage](https://github.com/soliton4/nodeMirror#usage) the editor does not load any files as shown in the picture
![nodeMirror loading loop](https://cloud.githubusercontent.com/assets/743075/14377662/48476fdc-fd71-11e5-97a7-fd958d1b175c.png)

Same result for Redhat 7 and Ubuntu 14.04.

I expected something like the first picture in the [Screenshot section](https://github.com/soliton4/nodeMirror#screenshots).

Are there any steps missing in the installation manual?

**Comment by soliton4** [comment]
try passing an absolute path to the --dir param. nm will have problems with missing rights or exotic file links

let me know if that helpex

**Comment by mhk** [comment]
Thx a lot. I missed the `dir` option.
